# Generated by Django 2.2.4 on 2019-08-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190805_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image_fun',
            new_name='image',
        ),
    ]
